### ISSUE TITLE
Rebuild APK with backups disabled

### ISSUE THREAD

**Issue by veggiedefender** [steamguard-totp/steamguard-shared-secret#1]
Leaving backups enabled is a [security vulnerability](https://github.com/signalapp/Signal-Android/issues/1387) and likely the reason Valve disabled it in the first place.

It should be easy to disable it after obtaining the shared secret, rebuilding the APK with the same keys, and installing that APK as an update.

**Comment by sigboe** [comment]
Just uninstall and reinstall the steam application, you lose Steam Guard notifications on your phone, but we don't want them anyway.

**Comment by whiteinge** [comment]
Thanks for the thought but sigboe is exactly right. This project is a one-time use to extract the shared secret so TOTP can be set up on an alternative authenticator. We decidedly do not want to maintain an alternative app to the official app. That would be bad for the reason you cited as well as the very notable problem that it wouldn't receive updates from the Play Store. I think the README makes the project goal clear but please do open a PR if you see room for improvement!
