### ISSUE TITLE
Disable Mobile Authenticator, how?

### ISSUE THREAD

**Issue by Atlas7005** [steamguard-totp/steamguard-shared-secret#7]
The instructions state that I have to disable the mobile authenticator, but how would I do that without completely removing it... It is my understanding from working with stuff like this in the past that if you remove it, any shared secret you have will be invalid?

So is there some other way I don't know of?

**Comment by whiteinge** [comment]
Those instructions refer to logging into the Steam website and disabling 2FA entirely for your **Steam account** -- not disabling the app. It's confusing because Steam refers to their 2FA solution and the app with the same terminology.

You're right that if you have 2FA enabled for your account and remove the app then the shared secret will be lost and you'll be locked out of your account so don't do that :scream:  ! You can re-enable 2FA for your Steam account after you extract the secret and set up a different authenticator.

**Comment by Atlas7005** [comment]
So what are the exact steps to "disable" it?

**Comment by whiteinge** [comment]
> So what are the exact steps to "disable" it?

If you log into Steam (the website, not the app), that configuration lives under 'Account Details -> Account Security'. I don't want to give more instructions than that.

I hope you don't mind me being blunt: if you're not very familiar with managing 2FA on various websites then I highly **recommend not using this project**. There is a distinct possibility that you'll accidentally get locked out of your Steam account. if that happens we can't help you, (and we're not liable,) and Steam support probably can't help you. If you proceed it's important to know that you're effectively gambling with permanently losing your Steam account. The official Steam app works well and is easy to use; this project is for crazy people that really, really, (really) want to use an alternative authenticator app. It's also very plausible that running the script in this repo won't work from start to finish on the first run -- computer development environments always have slight differences -- so using this code requires some technical and troubleshooting familiarity. I sincerely hope that doesn't sound harsh, and I don't want to be a jerk or a gatekeeper, but I feel it's important to emphasize the risk involved and to turn people away if this project doesn't sound like a good fit. Whatever path you take, I wish you good luck.

**Comment by Atlas7005** [comment]
I know the risk, so I think it's very important to give precise instruction to prevent people from messing up.
I understand you have no rude intentions. I don't think you have thought about what GitHub stands for, as it is for collaboration and helping each other.

I also have extensive experience with software development, troubleshooting, and general technicals.
