### ISSUE TITLE
Downgrade Steam App Grab Secret?

### ISSUE THREAD

**Issue by Twizzer** [steamguard-totp/steamguard-shared-secret#8]
Is it possible to downgrade your steam APK to like 2.1 or before and use this to grab the secret?

"You used to be able to just adb backup -f steam.ab -noapk com.valvesoftware.android.steam.community and get the shared_secret, but Valve fixed that."

**Comment by whiteinge** [comment]
Interesting question. I don't know the aOne worry is finding the right APK version from a reputable/safe source, another is whether Valve has changed any APIs the app communicates with since then, and yet another is whether Android still supports the APIs that version was built against. Still, it would be interesting to hear an answer.

**Comment by Twizzer** [comment]
I mean I could try not sure what will happen.

**Comment by whiteinge** [comment]
I guess I should rephrase: while it would be interesting to hear an answer to your question, I'd hesitate to recommend that path due to the security concerns around finding the APK. :-P

**Comment by Twizzer** [comment]
You can find unmolested apk's on certain sites.

**Comment by Twizzer** [comment]
@whiteinge I was able to backup steam.ab however if I open in notepad ++ it looks encrypted is there something to degarble the info? Right now there is no 2FA setup on my APK but I want to see if it will try at least.

**Comment by whiteinge** [comment]
@Twizzer Neat. When you initiate the backup the phone should prompt you to enter a passphrase for encryption. If you leave that blank the resulting .ab file won't be encrypted. The file format is a tar file with a weird file header. You can untar it with this command:

https://github.com/steamguard-totp/steamguard-shared-secret/blob/b305aa61233ed3b811f4b03803ebfa624ce082e8/get_code.sh#L83-L85

**Comment by Twizzer** [comment]
Would I need a program to untar it?

**Comment by whiteinge** [comment]
Yes, you'll need the `dd`, Python 3, and `tar` programs in that shell pipeline.

**Comment by Twizzer** [comment]
Yeah it let me do the backup but beyond that I'm out of my depth. If you want to try to work together to see if we can extract the require key we can.

Then you can have a new method. Also from 2.1 when I set it up I was able to update it to the newest version.

So everything is still working.

**Comment by Twizzer** [comment]
Then you might have a new method for people.
